name: JMeter Load Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-jmeter-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install JMeter
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.zip -OutFile jmeter.zip
          Expand-Archive -Path jmeter.zip -DestinationPath $Env:GITHUB_WORKSPACE\jmeter
          Remove-Item jmeter.zip

      - name: Run JMeter Test
        shell: pwsh
        run: |
          $jmeterPath = "$Env:GITHUB_WORKSPACE\\jmeter\\apache-jmeter-5.4.1\\bin\\jmeter.bat"
          $testFile = "$Env:GITHUB_WORKSPACE\\tests\\Test_1_example.com.jmx"
          $resultsDir = "$Env:GITHUB_WORKSPACE\\results"
          $resultsFile = "$resultsDir\\jmeter_results.jtl"
          $reportDir = "$resultsDir\\jmeter_report"

          New-Item -ItemType Directory -Force -Path $resultsDir
          & $jmeterPath -n -t $testFile -l $resultsFile -e -o $reportDir

          Write-Host "🔍 Result files:"
          Get-ChildItem -Recurse $resultsDir

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/
