name: JMeter Load Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-jmeter-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install JMeter
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.zip -OutFile jmeter.zip
          Expand-Archive -Path jmeter.zip -DestinationPath $Env:USERPROFILE
          Remove-Item jmeter.zip

      - name: Run JMeter Test
        shell: pwsh
        run: |
          $jmeterPath = "$Env:USERPROFILE\apache-jmeter-5.4.1\bin\jmeter.bat"
          $testFile = "tests\Test_1_example.com.jmx"
          $resultsFile = "results\jmeter_results.jtl"
          $reportFile = "results\jmeter_report.html"

          New-Item -ItemType Directory -Force -Path results
          & $jmeterPath -n -t $testFile -l $resultsFile -e -o $reportFile

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: results/
